//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DockStoreDBEntities : DbContext
    {


        public DockStoreDBEntities()
            : base("name=DockStoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static DockStoreDBEntities _context;
        public static DockStoreDBEntities GetContext()
        {
            if (_context == null)
                _context = new DockStoreDBEntities();
            return _context;
        }

        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
    }
}
