//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klient
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string PasportNum { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string DockTipe { get; set; }
        public string DockPath { get; set; }
    }
}
